Clean up Performance Tracking plugin settings code
xwp/site-performance-tracker pull request #75
Opened 2022-06-10 09:21 UTC by mykola

The settings page for the plugin has been added using code structure that doesn’t match the rest of the plugin. Refactor the code using the WordPress best practices and organize it to match the rest of the plugin code.

## Tasks

- [x] Move settings into class
- [ ] Extract strings into constants
- [ ] Remove code duplicates
- [ ] Enhance code

2022-08-25 15:19 UTC, emeaguiar requested changes
Hi @mykola, great work! I only had a couple of comments but if some other engineer wants to take a second look that would be fine

2022-08-25 15:19 UTC, emeaguiar commented on php/src/class-fieldbase.php
> +		global $tracker_config;
❓ **Question**: I see this global being call several times, I'm just not a fan of using `global`. Is there any chance we can use a function to call it instead?

<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution. -->

2022-08-25 15:19 UTC, emeaguiar commented on php/src/class-settings.php
> +			'Site Performance Tracker',
🗒️ **Todo:** Let's add translation functions here

<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement. -->

2022-08-25 15:19 UTC, emeaguiar commented on php/src/class-webvitalstrackingratiofield.php
> +			   placeholder="Enter between 0 > 1" aria-label="web vitals tracking ratio"
🗒️ **Todo:** Let's add translation functions here. And maybe some helper text to describe what does this do

<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement. -->

2022-08-26 11:09 UTC, tharsheblows reviewed
This feels so much more understandable now! I like the way it's set up. Most of my suggestions are about including translatable strings. The suggestion to use more constants for the names of things is a personal preference; I do like seeing everything up at the top. :)

2022-08-26 11:09 UTC, tharsheblows commented on php/src/class-settings.php
> +				<?php _e( 'You can get the <a href="https://web-vitals-report.web.app/" target="_blank">Web Vitals Report here</a>. Ensure that the date range starts from when the Web Vitals data is being sent.'
**❗️issue:** I would wrap the translation function in `sprintf()` with the opening tag of the link and closing tag of the link as placeholders.

2022-08-26 12:11 UTC, schlessera requested changes
For most of the issues, I flagged only the first occurrence I noticed, but they apply to all of their occurrences, of course (like terminating period for comments, `final` on classes, etc...).

The main issue I see is the use of a global that acts as class-internal data. This breaks the OOP principles and needs to be avoided, so I would suggest refactoring the `$tracker_config` into a more OOP-compatible way.

2022-08-26 12:11 UTC, schlessera commented on php/src/class-settings.php
> +		$tracker_config = isset( get_theme_support( self::HARDCODED_TRACKER_CONFIG_FEATURE )[0] ) ? get_theme_support( self::HARDCODED_TRACKER_CONFIG_FEATURE )[0] : array();
Classes should be planned to be extensible or not. If this is meant to be extensible, then the use of `self::` should be avoided as it would not provide the expected behavior if an extending class were to override these constants. The class should then use `static::` instead to make use of late static binding so the overriding constant gets used instead.
If the class is not planned to be extensible, then the use of `self::` is fine, but the class should be made `final`.

So, the defaults should be either `final`, `private` & `self::`, or `! final`, `protected` and `static::`.

2022-08-26 12:11 UTC, schlessera commented on phpcs.xml.dist
> +	<exclude-pattern>/.history/</exclude-pattern>
This should not be here as it is unrelated to the project.

2022-12-05 16:37 UTC, mehigh approved these changes
Thank you for handling the feedback!

2022-12-05 16:37 UTC, merged